Fix to use released scala-parser-combinators artifacts for Scala 2.11
Looks like version 1.0.0 of scala-parser-combinators was never
published to Maven Central:

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.scala-lang.modules%22%20AND%20a%3A%22scala-parser-combinators_2.11%22

You can see how this causes problems with this example build of The BFG:

https://travis-ci.org/rtyley/bfg-repo-cleaner/builds/24380719

```
sbt.ResolveException: unresolved dependency: org.scala-lang.modules#scala-parser-combinators_2.11;1.0.0: not found
```