Update to Scala 2.10.0 final
http://www.scala-lang.org/node/27499

This update compiles and passes tests without problems.

Incidentally, I've tried using the published scala-io-file_2.10 v0.4.1
artifact in a 2.10-based project, but unfortunately it fails:

http://search.maven.org/#artifactdetails|com.github.scala-incubator.io|scala-io-file_2.10|0.4.1|jar

java.lang.NoSuchMethodError: scala.LowPriorityImplicits.charWrapper(C)Lscala/runtime/RichChar;
	at scalax.file.FileSystem.<init>(FileSystem.scala:49)
	at scalax.file.defaultfs.DefaultFileSystem.<init>(DefaultFileSystem.scala:20)

In Scala 2.10.0 that set of methods are now inlined, presumably
causing the NoSuchMethodError:

https://github.com/scala/scala/commit/d3f879a#diff-0

Recompiling against Scala 2.10.0 should fix it, I think!